refactor shell scripts

diff --git a/bin/verify-exercises b/bin/verify-exercises
--- a/bin/verify-exercises
+++ b/bin/verify-exercises
@@ -19,33 +19,33 @@ verify_exercise() {
     exercises_path="$repo/exercises/$1/$slug"
     source_file_name="$2"
     tmp_file=$(mktemp)
-    
+    trap 'rm $tmp_file' EXIT INT TERM
+
     for exercise_dir in $exercises_path; do
         if [ -z "$exercise_dir" ]; then
             continue
         fi
-        
-        echo "Checking $(basename "$exercise_dir") exercise..."
-        
+
+        exercise=$(basename "$exercise_dir")
+        echo "Checking $exercise exercise..."
+
         cd "$exercise_dir" || exit 1
-        
+
         solution_file=".meta/$source_file_name.cairo"
         if [ -z "$solution_file" ]; then
-            echo "Could not find solution for $1"
+            echo "Could not find solution file for $exercise"
             exit 1
         fi
-        
+
         # since we're testing the solution, we need to temporarily replace
         # the exercise's solution files with its exemplar/example files
         cp "$lib_cairo" "$tmp_file"
         cp "$solution_file" "$lib_cairo"
-        
+
         scarb cairo-test
-        
+
         cp "$tmp_file" "$lib_cairo"
     done
-    
-    rm "$tmp_file"
 }
 
 # https://github.com/exercism/docs/blob/main/anatomy/tracks/concept-exercises.md#file-exemplar-implementation
